# -*- coding: utf-8 -*-
"""glass_model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R12BsHQYU9kX9pd0DAUy9sd4SBQFYYuB
"""

#Installation de Pycaret
!pip install pycaret

import pandas as pd
from pycaret.regression import *

df = pd.read_csv('/content/drive/My Drive/cleaned_dataset.csv')
df.head()

df.shape

df.columns

df_best = df[[ 'avg_sal','Rating', 'Size', 
       'Type of ownership', 'Industry', 'Sector', 'Revenue', 
       'hourly', 'emp_provided', 
       'state', 'same_state', 'company_age', 'python', 'sql',
       'spark', 'java', 'tableau', 'excel', 'hadoop', 'powerbi', 'aws',
       'nosql', 'num_comp', 'job_simp', 'seniority']]

#On va retirer pres de 100 observations que le modele ne connaitra pas
df_model= df_best.sample(frac=0.91, random_state=42).reset_index(drop=True)
df_unseen= df_best.drop(df_model.index).reset_index(drop=True)
print('Dataset pour le model: ' + str(df_model.shape))
print('Dataset non vu pour les futures predictions: ' + str(df_unseen.shape))

#Configuration du dataset pour pycaret
df = setup(data= df_model, target='avg_sal', session_id=16, normalize=True, 
           ignore_low_variance=True,remove_multicollinearity = True, multicollinearity_threshold = 0.95,
            feature_selection=True, bin_numeric_features=['company_age'])

#Comparaison des models
compare_models()

# CREATION DES MODELES
# CatBoost
cat= create_model('catboost')

tunned_cat= tune_model('catboost')

interpret_model(tunned_cat, plot = 'summary')

#RANDOM FOREST
rf= create_model('rf')
print(rf)

tunned_rf = tune_model('rf')
print(tunned_rf)

plot_model(rf, plot = 'parameter')

bagged_cat = ensemble_model(tunned_cat)

blend_specific = blend_models(estimator_list = [tunned_cat, rf])

predict_model(blend_specific)

final_model = finalize_model(blend_specific)

unseen_predictions = predict_model(final_model, data=df_unseen, round=0)
unseen_predictions.head()

save_model(final_model, 'blended_rf_cat')

evaluate_model(final_model)



